// using System.Text;
//
// namespace StateController
// {
//     public static class CodeGenerator
//     {
//         private const string StartText = "// This is automatically generated by StateController. Please do not modify it.";
//         public static StringBuilder GetStateText(StateController controller, string prefix)
//         {
//             StringBuilder stringBuilder = new StringBuilder();
//             stringBuilder.Append("// This is automatically generated by StateController. Please do not modify it.");
//             stringBuilder.Append("");
//         }
//     }
// }